<a href="https://colab.research.google.com/github/nikhilcn-ec/Machine_learning/blob/main/numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy and basics

In [ ]:
import numpy as np

# np.array() to create a array

a=np.array([1,2,3])
b=np.array([[1,2],[4,5]])


[[1 2]
 [4 5]]


In [ ]:
# ndim returns dimension of array
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# return shape of array in numpy
a.shape

(3,)

In [ ]:
b.shape

(2, 2)

In [ ]:
# return datatype of numpy array
a.dtype

dtype('int64')

In [ ]:
# returns the size of each element in the array
a.itemsize

8

Slicing in Numpy

In [ ]:
arr=np.array([[1,2,0],[3,4,1],[5,6,3]])
#returns specific row and all columns
r=arr[1,:]
print(r)

[3 4 1]


In [ ]:
e=arr[:,0]
# returns specific cloumn and all rows
print(e)

[1 3 5]


In [ ]:
z=arr[0,2]
# returns specific column and specific row
print(z)

0


different initialization of numpy arrays

In [ ]:
# np.zeros creates a new array filled with all zeros.
zero_arr=np.zeros(5)
print(zero_arr)

[0. 0. 0. 0. 0.]


In [ ]:
z_arr=np.zeros((2,3))
print(z_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# np.ones creates a new array filled with all ones.
one_arr=np.ones((2,2))
print(one_arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
# p.full creates a new array filled with any value you want — not just 0 or 1.
full_arr=np.full((3,2),9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]


In [ ]:
# np.random.rand() generates an array of random numbers between 0 and 1 (from a uniform distribution).
rand_arr=np.random.rand(2,3)
print(rand_arr)

[[0.22612794 0.7783412  0.3579951 ]
 [0.43797484 0.26897048 0.16835978]]


In [ ]:
# np.random.randint() generates random integers between a start (inclusive) and an end (exclusive).
rand_int=np.random.randint(1,10,size=(3,3))
print(rand_int)


[[5 7 9]
 [8 2 5]
 [8 9 1]]


In [ ]:
# np.identity() creates a square matrix (same number of rows and columns) with:

# 1s on the main diagonal (top-left to bottom-right)

# 0s everywhere else
indentity_arr=np.identity(3)
print(indentity_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Reorganizing arrays

In [ ]:
# Rearranges the elements of an array into a new shape (without changing the data).

arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(arr)
print(new_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacks arrays vertically (one on top of another).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.vstack((arr1, arr2))
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacks arrays horizontally (one beside the other).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.hstack((arr1, arr2))
print(stacked_arr)

[1 2 3 4 5 6]


load data from file

In [ ]:
# np.genfromtxt() is used to load data from a text file (like .csv or .txt), and it's great for handling files with missing or inconsistent data.
data = np.genfromtxt('file.txt', delimiter=',')
print(data)

[1. 2. 3. 4. 4. 5. 5. 6. 6. 7. 7.]


In [ ]:
# astype() is used to change the data type of an existing NumPy array.
org_arr=np.array([1.3,4.5,6.7])
print(F"float type array:{org_arr}")
typ_arr=arr.astype(int)
print(F"int type array:{typ_arr}")

float type array:[1.3 4.5 6.7]
int type array:[1 2 3 4 5 6]


In [ ]:
# data[data > value]
# This is a boolean indexing technique. It filters the array based on a condition.
fill_arr=typ_arr[typ_arr<4]
print(fill_arr)

[1 2 3]


Basic Mathematical Functions: sin() and cos()

In [ ]:
# np.sin()
# Calculates the sine of each element in the array.
arr = np.array([0, np.pi/2, np.pi])  # angles in radians
sin_values = np.sin(arr)
print(arr)
print(sin_values.astype(int))


[0.         1.57079633 3.14159265]
[0 1 0]


In [ ]:
arr = np.array([0, np.pi/2, np.pi])
cos_values = np.cos(arr)
print(cos_values.astype(int))

[ 1  0 -1]


Linear Algebra: matmul() and linalg

In [ ]:
# np.matmul()
# Performs matrix multiplication (also works for dot products of vectors).
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.matmul(A, B)
print(result)


[[19 22]
 [43 50]]


In [ ]:
#  np.linalg.det()
# Calculates the determinant of a matrix.
A = np.array([[1, 2], [3, 4]])

det = np.linalg.det(A)
print(det.astype(int))



-2


 Statistics: max(), min(), and sum()

In [ ]:
# np.max()
# Returns the maximum value in an array.
arr = np.array([1, 2, 3, 4, 5])
max_value = np.max(arr)
min_value = np.min(arr)
sum=np.sum(arr)
print(sum)
print(min_value)
print(max_value)


15
1
5
